# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
import test_runner
import test_recorder
import test_organizer

class Ui_MainWindow(object):
    stored_tests = os.listdir("test_steps")
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(640, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rec_button = QtWidgets.QPushButton(self.centralwidget)
        self.rec_button.setGeometry(QtCore.QRect(20, 40, 180, 60))
        self.rec_button.setCheckable(True)
        self.rec_button.setObjectName("rec_button")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(20, 130, 180, 60))
        self.run_button.setCheckable(True)
        self.run_button.setObjectName("run_button")
        self.org_button = QtWidgets.QPushButton(self.centralwidget)
        self.org_button.setGeometry(QtCore.QRect(20, 220, 180, 60))
        self.org_button.setCheckable(True)
        self.org_button.setObjectName("org_button")
        self.test_case_sel = QtWidgets.QPushButton(self.centralwidget)
        self.test_case_sel.setGeometry(QtCore.QRect(430, 330, 101, 31))
        self.test_case_sel.setObjectName("test_case_sel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(440, 30, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setObjectName("label")
        self.test_name = QtWidgets.QTextEdit(self.centralwidget)
        self.test_name.setGeometry(QtCore.QRect(230, 70, 151, 41))
        self.test_name.setObjectName("test_name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 30, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.test_name_ok = QtWidgets.QPushButton(self.centralwidget)
        self.test_name_ok.setGeometry(QtCore.QRect(230, 120, 91, 31))
        self.test_name_ok.setObjectName("test_name_ok")
        self.test_list = QtWidgets.QListWidget(self.centralwidget)
        self.test_list.setGeometry(QtCore.QRect(440, 70, 181, 251))
        self.test_list.setObjectName("test_list")
        self.test_case_del = QtWidgets.QPushButton(self.centralwidget)
        self.test_case_del.setGeometry(QtCore.QRect(530, 330, 101, 31))
        self.test_case_del.setObjectName("test_case_del")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.hide_UI()
        self.populate_tests()
        self.rec_button.clicked.connect(self.test_rec)
        self.run_button.clicked.connect(self.test_run)
        self.org_button.clicked.connect(self.test_org)
        self.test_case_sel.clicked.connect(self.select_test)
        self.test_case_del.clicked.connect(self.delete_test)
        self.test_name_ok.clicked.connect(self.rec_new_test)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rec_button.setText(_translate("MainWindow", "Test Recorder"))
        self.run_button.setText(_translate("MainWindow", "Test Runner"))
        self.org_button.setText(_translate("MainWindow", "Test Organizer"))
        self.test_case_sel.setText(_translate("MainWindow", "Run"))
        self.label.setText(_translate("MainWindow", "Test cases"))
        self.label_2.setText(_translate("MainWindow", "Enter test name"))
        self.test_name_ok.setText(_translate("MainWindow", "Start"))
        self.test_case_del.setText(_translate("MainWindow", "Delete"))
        
    def hide_UI(self):
        self.test_name.hide()
        self.test_name_ok.hide()
        self.label_2.hide()
        
        self.test_list.hide()
        self.test_case_sel.hide()
        self.test_case_del.hide()
        self.label.hide()
        
    def populate_tests(self):
        for i in range(len(self.stored_tests)):
            self.test_list.addItem(self.stored_tests[i])
    
    def test_rec(self):
        self.hide_UI()
        if self.rec_button.isChecked():
            if self.run_button.isChecked():
                self.run_button.toggle()
            if self.org_button.isChecked():
                self.org_button.toggle()
            self.test_name.show()
            self.test_name_ok.show()
            self.label_2.show()
            
            self.test_list.show()
            self.label.show()
        else:
            self.test_name.hide()
            self.test_name_ok.hide()
            self.label_2.hide()
            
            self.test_list.hide()
            self.label.hide()
            
    def test_run(self):
        self.hide_UI()
        if self.run_button.isChecked():
            if self.rec_button.isChecked():
                self.rec_button.toggle()
            if self.org_button.isChecked():
                self.org_button.toggle()
            self.test_list.show()
            self.test_case_sel.show()
            self.label.show()
            
        else:
            self.test_list.hide()
            self.test_case_sel.hide()
            self.label.hide()
            
    def test_org(self):
        self.hide_UI()
        if self.org_button.isChecked():
            if self.rec_button.isChecked():
                self.rec_button.toggle()
            if self.run_button.isChecked():
                self.run_button.toggle()
            self.test_list.show()
            self.test_case_del.show()
            self.label.show()
            
        else:
            self.test_list.hide()
            self.test_case_del.hide()
            self.label.hide()

    def select_test(self):
        value = self.test_list.currentRow()
        print(self.stored_tests[value])
        test_runner.run(self.stored_tests[value])
        
    def rec_new_test(self):
        name = self.test_name.toPlainText()
        #print(name)
        if name != "":
            print(name)
            test_recorder.rec(name)
            self.test_list.addItem(name)
        else:
            print("Test name cannot be empty")
            
    def delete_test(self):
        value = self.test_list.currentRow()
        print(self.stored_tests[value])
        test_organizer.clear_dir(self.stored_tests[value])
        self.test_list.takeItem(value)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
